[INFO|load_soc_definitions.py|main|L52] @ 2025-01-04 07:34:46,527: Index(['SOC Code', 'SOC Group', 'SOC Title', 'SOC Definition'], dtype='object')
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:36:22,385: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:36:36,451: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:37:12,194: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:38:20,565: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:40:07,555: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:40:22,881: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:40:32,190: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:43:02,428: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L65] @ 2025-01-04 07:43:02,655: Validating definitions was successful. Recording metadata.
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:43:16,873: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L65] @ 2025-01-04 07:43:16,950: Validating definitions was successful. Recording metadata.
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:43:30,582: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L65] @ 2025-01-04 07:43:30,660: Validating definitions was successful. Recording metadata.
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:43:52,325: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L65] @ 2025-01-04 07:43:52,399: Validating definitions was successful. Recording metadata.
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:44:33,033: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L65] @ 2025-01-04 07:44:33,107: Validating definitions was successful. Recording metadata.
[INFO|load_soc_definitions.py|main|L72] @ 2025-01-04 07:44:33,135: Connected to metadata schema.
[INFO|capture.py|record_metadata|L17] @ 2025-01-04 07:44:33,136: Reached record_metadata function.
[INFO|load_soc_definitions.py|main|L60] @ 2025-01-04 07:45:33,884: Cleaning definitions was successful validating schema.
[INFO|load_soc_definitions.py|main|L72] @ 2025-01-04 07:45:33,920: Connected to metadata schema.
[INFO|capture.py|record_metadata|L17] @ 2025-01-04 07:45:33,921: Reached record_metadata function.
